### ISSUE TITLE
大佬，这是怎么回事?求解

### ISSUE THREAD

**Issue by ghost** [nowscott/EverydayTechNews#3]
![error](https://github.com/nowscott/EverydayTechNews/assets/158043341/39387d6f-ed8d-40ab-a0c2-faabbe72f212)

**Comment by nowscott** [comment]
是这样的，目前我的邮件列表是放在notion上的，这个readme文档有一段时间没更新了，方便的话邮件沟通，这里我可能会看不到，nowscott@qq.com

**Comment by nowscott** [comment]
我等下更新一下readme文档中的部署方式
